services:
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/usr/src/app
      - node_modules_node_prompter:/usr/src/app/node_modules
    ports:
      - "5173:5173"

volumes:
  node_modules_node_prompter: